# Read data from database

In [121]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

In [122]:
load_dotenv('../.env')
USERNAME = os.getenv('DB_USERNAME')
PASSWORD = os.getenv('PASSWORD')
HOST = os.getenv('HOST')
PORT = os.getenv('PORT')
DATABASE = os.getenv('DATABASE')

In [123]:
print(DATABASE)
print(USERNAME)
print(PASSWORD)
print(HOST)
print(PORT)

basketball_db
root
Parsamysql1379
localhost
3306

In [124]:
engine = create_engine(f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}")

champion_team_player_df = pd.read_sql('SELECT * FROM championteamplayer', engine)
college_df              = pd.read_sql('SELECT * FROM college', engine)
country_df              = pd.read_sql('SELECT * FROM country', engine)
mvp_award_df            = pd.read_sql('SELECT * FROM mvp_award', engine)
player_df               = pd.read_sql('SELECT * FROM player', engine)
player_college_df       = pd.read_sql('SELECT * FROM playercollege', engine)
player_position_df      = pd.read_sql('SELECT * FROM playerposition', engine)
player_season_stats_df  = pd.read_sql('SELECT * FROM playerseasonstats', engine)
positions_df            = pd.read_sql('SELECT * FROM positions', engine)
season_df               = pd.read_sql('SELECT * FROM season', engine)
team_df                 = pd.read_sql('SELECT * FROM team', engine)

# Preprocessing

### champion_team_player_df

In [125]:
champion_team_player_df.head()

   player_id  season_id team_code
0  adamsja01          2       MIL
1  antetgi01          2       MIL
2  antetth01          2       MIL
3  augusdj01          2       MIL
4  bryanel01          2       MIL

### college_df

In [129]:
college_df.head()

   college_id            college_name
0           1     1985in College Park
1           2       Acadia University
2           3               Air Force
3           4                 Alabama
4           5  Alabama A&M University

### country

In [132]:
country_df.head()

   country_id country_name
0           1           ag
1           2           ao
2           3           ar
3           4           at
4           5           au

### mvp_award_df

In [135]:
mvp_award_df.head()

   player_id  season_id  mvp_rank  mvp_share
0  antetgi01          1       1.0      0.952
1  jamesle01          1       2.0      0.746
2  hardeja01          1       3.0      0.363
3  doncilu01          1       4.0      0.198
4  leonaka01          1       5.0      0.166

### player_df

In [142]:
player_df.head()

,player_id,full_name,birth_date,birth_place,height_cm,weight_kg,shoots,player_url,country_id
0,abdelal01,Alaa Abdelnaby,1968-06-24,"Cairo,Egypteg",208,108.0,Right,https://www.basketball-reference.com/players/a...,27
1,abdulka01,Kareem Abdul-Jabbar,1947-04-16,"New York,New Yorkus",218,102.0,Right,https://www.basketball-reference.com/players/a...,86
2,abdulma01,Walt Hazzard,1942-04-15,"Wilmington,Delawareus",188,83.0,Right,https://www.basketball-reference.com/players/a...,86
3,abdulma02,Mahmoud Abdul-Rauf,1969-03-09,"Gulfport,Mississippius",185,73.0,Right,https://www.basketball-reference.com/players/a...,86
4,abdulta01,Tariq Abdul-Wahad,1974-11-03,"Maisons Alfort,Francefr",198,101.0,Right,https://www.basketball-reference.com/players/a...,30

### player_college_df

In [147]:
player_college_df.head()

   player_id  college_id
0  aubucch01         326
1  willial06         538
2  willial06         407
3  willial06         623
4  barnhle01         398

### player_position_df

In [150]:
player_position_df.head()

   player_id  position_id
0  aubucch01            3
1  willial06            7
2  barnhle01            6
3  morriis01            6
4  jacksja01            7

### player_season_stats_df

In [153]:
player_season_stats_df.head()

,player_id,season_id,team_code,age,games,games_started,minutes,win_shares,ws_per_48,bpm,vorp
0,hardeja01,1,HOU,30,68,68,2483,13.1,0.254,9.6,7.3
1,lillada01,1,POR,29,66,66,2474,11.6,0.225,7.5,5.9
2,antetgi01,1,MIL,25,63,63,1917,11.1,0.279,11.5,6.6
3,davisan02,1,LAL,26,62,62,2131,11.1,0.250,8.0,5.4
4,goberru01,1,UTA,27,68,68,2333,10.7,0.221,3.6,3.3

In [154]:
player_season_stats_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2785 entries, 0 to 2784
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   player_id      2785 non-null   str
 1   season_id      2785 non-null   int64
 2   team_code      2785 non-null   str
 3   age            2785 non-null   int64
 4   games          2785 non-null   int64
 5   games_started  2785 non-null   int64
 6   minutes        2785 non-null   int64
 7   win_shares     2785 non-null   float64
 8   ws_per_48      2785 non-null   float64
 9   bpm            2785 non-null   float64
 10  vorp           2785 non-null   float64
dtypes: float64(4), int64(5), str(2)
memory usage: 239.5 KB

### positions_df

In [157]:
positions_df

    position_id position_name
0             1             C
1             2             F
2             3             G
3             4            PF
4             5            PG
5             6            SF
6             7            SG
7             1             C
8             2             F
9             3             G
10            4            PF
11            5            PG
12            6            SF
13            7            SG

### season_df

In [160]:
season_df.head()

   season_id season_name
0          1     2019-20
1          2     2020-21
2          3     2021-22
3          4     2022-23
4          5     2023-24

### team_df

In [162]:
team_df.head()

   team_id team_code team_name
0        1       2TM      None
1        2       3TM      None
2        3       4TM      None
3        4       ATL      None
4        5       BOS      None